name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 👈 Cambia a 'master' si tu rama se llama así

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # 👈 ¡Corregido el punto aquí!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto compilado
        uses: actions/upload-pages-artifact@v3
        with:
          # Pon aquí la ruta exacta a tu carpeta compilada dentro de dist
          path: 'dist/app-angular' 

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4