name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 👈 Cambia a 'master' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/app-angular # 👈 Cambia esto por el nombre de la carpeta que hay dentro de dist/
          branch: gh-pages